manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 7e7214237d032c8eec0e1cf326a0b4fbe2cba34d
      import: app/west.yml
  self:
    path: config
