manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: a261326b31cb6d3d14a8539bb693da5a068c64c8
      import: app/west.yml
  self:
    path: config
